#!/bin/bash

user_name="$(logname)"

post_install() {
    xdg-icon-resource forceupdate --theme hicolor &> /dev/null
    update-desktop-database -q
    
    if [ ! -f /home/${user_name}/.local/share/ktorrent ]; then
        mkdir -p /home/${user_name}/.local/share/ktorrent
        chown -R ${user_name}:users /home/${user_name}/.local/share/ktorrent
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
