--- a/doc/Makefile	2016-04-11 18:19:52.619724748 -0400
+++ b/doc/Makefile_new	2016-04-11 18:25:49.970679442 -0400
@@ -468,7 +468,7 @@
 
 install-data-local:
 	$(MKDIR_P) "$(DESTDIR)$(docdir)/html/search"  ## Didn't work with installdirs-local
-	$(INSTALL_DATA) html/*.css html/*.html html/*.js html/*.map html/*.md5 html/*.png "$(DESTDIR)$(docdir)/html/"
+	$(INSTALL_DATA) html/*.css html/*.html html/*.js html/*.md5 html/*.png "$(DESTDIR)$(docdir)/html/"
 	$(INSTALL_DATA) html/search/* "$(DESTDIR)$(docdir)/html/search/"
 	-$(INSTALL_DATA) *.qch "$(DESTDIR)$(docdir)/"
 
