#!/bin/bash
# tputcolors

user_name="$(logname)"

post_install() {
    echo -e '\e[1;34m To install this plasmoid for your user run:'
    echo -e '\e[1;34m plasmapkg2 -i /usr/share/plasma/plasmoids/com.librehat.yahooweather'
    echo -e '\e[1;34m Fill in your city WOEID* in the configuration dialog under General Settings \e[0m'
    
}

post_upgrade() {
    echo -e '\e[1;34m To upgrade this plasmoid for your user run:'
    echo -e '\e[1;34m plasmapkg2 -u  /usr/share/plasma/plasmoids/com.librehat.yahooweather \e[0m'
}