#!/bin/bash

job_rcconf_network()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_rcconf_network"

	msg "add networkmanager settings"

	# set devices to dhcp, needed for networkmanager
	sed -i -e 's/^.*eth0=.*/eth0="dhcp"/' ${mountpoint}/etc/rc.conf

	msg "set the hostname"
	if [ "${hostname}" != "" ] ; then
		msg "adding hostname: ${hostname}"
		sed -i -e "s/^.*HOSTNAME=.*/HOSTNAME="\"${hostname}"\"/" ${mountpoint}/etc/rc.conf
		msg "updating /etc/hosts"
		sed -i -e 's/^[ \t]*127.0.0.1.*/127.0.0.1\tlocalhost.localdomain\tlocalhost\t'${hostname}'/' ${mountpoint}/etc/hosts
	else
		msg "adding hostname: chakra (no hostname specified)"
		sed -i -e 's/^.*HOSTNAME=.*/HOSTNAME="chakra"/' ${mountpoint}/etc/rc.conf
		msg "updating /etc/hosts"
		sed -i -e 's/^[ \t]*127.0.0.1.*/127.0.0.1\tlocalhost.localdomain\tlocalhost\tchakra/' ${mountpoint}/etc/hosts
	fi

	if [ -e "/usr/share/zsh/site-functions/_rc.d" ] ; then
		msg "initscripts: 2011.09: network interfaces will be configured by networkmanager/wicd"
	else
		msg "initscripts: 2011.04: add network interfaces"
		sed -i -e 's/^.*INTERFACES=.*/INTERFACES=(!eth0 !eth1 !wlan0)/' ${mountpoint}/etc/rc.conf
	fi

	# add networkmanagement or wicd to DAEMONS=
	if [ -f "${mountpoint}/usr/share/kde4/services/kcm_networkmanagement.desktop" ];
	then
		msg "adding networkmanager daemons"
		sed -i -e 's/^.*DAEMONS=.*/DAEMONS=(syslog-ng dbus !network networkmanager netfs crond avahi-daemon avahi-dnsconfd alsa cdemud)/' ${mountpoint}/etc/rc.conf
		# fix /etc/NetworkManager/nm-system-settings.conf
		echo " " >> ${mountpoint}/etc/NetworkManager/nm-system-settings.conf
		echo "[keyfile]" >> ${mountpoint}/etc/NetworkManager/nm-system-settings.conf
		echo "hostname=${hostname}" >> ${mountpoint}/etc/NetworkManager/nm-system-settings.conf
	else
		msg "adding wicd daemons"
		sed -i -e 's/^.*DAEMONS=.*/DAEMONS=(syslog-ng dbus !network wicd netfs crond avahi-daemon avahi-dnsconfd alsa cdemud)/' ${mountpoint}/etc/rc.conf
	fi
	msg_job_done
}
