#!/bin/bash

job_install_grub2()
{
    trap error_handler ERR

    msg_job_start "job_install_grub2"

    msg "mount chroot"
    mount -v -t proc none ${mountpoint}/proc
    mount -v -t sysfs none ${mountpoint}/sys
    mount -v -o bind /dev ${mountpoint}/dev
    mount -v -o bind /dev/pts ${mountpoint}/dev/pts

    msg "installing grub"
    _device=$(echo ${target_boot} | cut -b1-3)
    echo "GRUB2___ >>>> mountpoint: ${mountpoint}"
    echo "GRUB2___ >>>> target_boot: ${target_boot}"
    echo "GRUB2___ >>>> device: ${_device}"
    chroot ${mountpoint} grub-install /dev/${_device} --no-floppy > /tmp/grub2.log 2>&1

    if [ -e "/tmp/catalyst" ] ; then
       msg "Adding nomodeset for catalyst to kernel line"
       sed -i -e "s,GRUB_CMDLINE_LINUX_DEFAULT=.*,GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash radeon.modeset=0\",g" ${mountpoint}/etc/default/grub
       sed -i -e "s,GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash radeon.modeset=0\",g" ${mountpoint}/etc/default/grub
    fi

    msg "generating []/boot/grub/grub.cfg"
    chroot ${mountpoint} grub-mkconfig -o /boot/grub/grub.cfg --skip-resume >> /tmp/grub2.log 2>&1

    if [ "${use_swap}" = "yes" ] ; then
       msg "we are using swap partition"
       _sdevice=`echo /dev/${target_swap}`
       _suuid=`blkid "${_sdevice}" -s UUID -o value`
       sed -i -e "s~root=/dev/~resume=/dev/disk/by-uuid/${_suuid} root=/dev/~g" ${mountpoint}/boot/grub/grub.cfg
    fi

    msg "umounting /proc, /sys, /dev/pts and /dev"
    umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev/pts ${mountpoint}/dev

    msg_job_done
}
