#!/bin/bash

job_configure_sudoers()
{
	msg_job_start "job_configure_sudoers"

	# add given user to sudoers
	msg "adding the user to sudoers"
	echo >>${mountpoint}/etc/sudoers
	echo "# user created during chakra setup" >>${mountpoint}/etc/sudoers
	echo "${user_name}     ALL=(ALL) ALL" >>${mountpoint}/etc/sudoers
	echo >>${mountpoint}/etc/sudoers

	# CINSTALL STUFF

	# add cinstall settings
	echo "deleting any bundle settings"
	sed -i -e '/^.*%bundle.*/d' ${mountpoint}/etc/sudoers
	echo "adding the bundle setting"
	echo "%bundle ALL=NOPASSWD: /bin/mount -o loop -t squashfs *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /bin/mount -o loop -t ext4 *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /bin/umount *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /usr/bin/pacman -Sy" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /usr/bin/yaourt -Sy" >> ${mountpoint}/etc/sudoers

	# ensure correct permissions
	msg "ensure correct sudoers permissions"
	chmod -v 0440 ${mountpoint}/etc/sudoers

	msg_job_done
}