#!/bin/bash

job_create_initrd()
{
    # initialize error handling
    trap error_handler ERR

    msg_job_start "job_create_initrd"

    # check additional options
    if [ -e "/tmp/tribe_initcpio_enable_usb" ] ; then
    HWPARAMETER="$HWPARAMETER --usb"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_firewire" ] ; then
    HWPARAMETER="$HWPARAMETER --fw"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_pcmcia" ] ; then
    HWPARAMETER="$HWPARAMETER --pcmcia"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_nfs" ] ; then
    HWPARAMETER="$HWPARAMETER --nfs"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_softwarreraid" ] ; then
    HWPARAMETER="$HWPARAMETER --raid"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_softwareraidmdp" ] ; then
    HWPARAMETER="$HWPARAMETER --raid-partitions"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_lvm2" ] ; then
    HWPARAMETER="$HWPARAMETER --lvm2"
    fi

    if [ -e "/tmp/tribe_initcpio_enable_encrypted" ] ; then
    HWPARAMETER="$HWPARAMETER --encrypt"
    fi

    # setup mkinitcpio.conf
    msg "setup mkinitcpio.conf"
    HWPARAMETER="$HWPARAMETER --keymap"
    HWDETECTHOSTCONTROLLER=""
    HWDETECTHOOKS=""
    HWDETECTHOSTCONTROLLER="$(hwdetect --hostcontroller $HWPARAMETER)"
    HWDETECTHOOKS="$(hwdetect --hooks-dir=${mountpoint}/usr/lib/initcpio/install --hooks $HWPARAMETER)"
    [ -n "$HWDETECTHOSTCONTROLLER" ] && sed -i -e "s/^MODULES=.*/$HWDETECTHOSTCONTROLLER/g" ${mountpoint}/etc/mkinitcpio.conf
    [ -n "$HWDETECTHOOKS" ] && sed -i -e "s/^HOOKS=.*/$HWDETECTHOOKS/g" ${mountpoint}/etc/mkinitcpio.conf
    sed -i -e "s~filesystems~resume filesystems~g" ${mountpoint}/etc/mkinitcpio.conf

    msg "mounting /proc, /sys and /dev"
    mount -v -t proc none ${mountpoint}/proc
    mount -v -t sysfs none ${mountpoint}/sys
    mount -v -o bind /dev ${mountpoint}/dev

    touch /tmp/tribe-mkinitcpio-running

    #echo ":: copying kernel(s) to target ..." >> /tmp/initramfs.log; echo >> /tmp/initramfs.log
    #if [ -e "/boot/vmlinuz-linux" ] ; then
    #cp -vf /boot/vmlinuz-linux ${mountpoint}/boot/vmlinuz-linux >> /tmp/initramfs.log; echo >> /tmp/initramfs.log
    #fi
    #if [ -e "/boot/vmlinuz-linux-lts" ] ; then
    #cp -vf /boot/vmlinuz-linux-lts ${mountpoint}/boot/vmlinuz-linux-lts >> /tmp/initramfs.log; echo >> /tmp/initramfs.log
    #fi

    echo ":: starting initramfs creation..." >> /tmp/initramfs.log; echo >> /tmp/initramfs.log

    msg "creating initrd images"
    if [ -e "/boot/vmlinuz-linux" ] ; then
    chroot ${mountpoint} /sbin/mkinitcpio -p linux >>/tmp/initramfs.log 2>&1
    echo >> /tmp/initramfs.log
    fi
    if [ -e "/boot/vmlinuz-linux-lts" ] ; then
    chroot ${mountpoint} /sbin/mkinitcpio -p linux-lts >>/tmp/initramfs.log 2>&1
    echo >> /tmp/initramfs.log
    fi

    msg "creating loop devices"
    for i in $(seq 8 255)
    do
         chroot ${mountpoint} /bin/bash -c "mknod -m0660 /dev/loop$i b 7 $i; chown root.disk /dev/loop$i;"
    done

    rm -f /tmp/tribe-mkinitcpio-running

    msg "umounting /proc, /sys and /dev"
    umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev

    msg_job_done
}
