#!/bin/bash

job_pre_install()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_pre_install"

	mount -v -t proc none ${mountpoint}/proc 
	mount -v -t sysfs none ${mountpoint}/sys 
	mount -v -o bind /dev ${mountpoint}/dev 

	# remove any db.lck
	chroot ${mountpoint} /bin/rm -f /var/lib/pacman/db.lck
	
	msg "running pacman "

	for p in ${INSTALL_PACKAGES}
	do
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/${p}-* --noconfirm
	done

	msg "install /etc/inittab"
	cp -vf /etc/inittab ${mountpoint}/etc/inittab
	
	msg "umounting /proc, /sys and /dev"
	umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev 

	msg_job_done
}
