# Some colored makepkg-like functions
#!/bin/bash
# tputcolors
post_install() {
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
  
  echo -e '\e[34m Minitube has known issues with phonon-gstreamer'
  echo -e '\e[34m Set phonon-vlc as default backend in systemsettings > multimedia \e[0m'

}

post_upgrade() {
  post_install
}

post_remove() {
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}
