# Some colored makepkg-like functions
#!/bin/bash
# tputcolors
post_install() {
	post_upgrade
}

post_upgrade() {
	  echo -e '\e[0;32m To have better integration with KaOS'
          echo -e '\e[0;32m Please download and use the KaOS.crx:' 
          echo -e '\e[0;32m http://sourceforge.net/projects/kaosx/files/sources/chrome-themes/KaOS.crx'
          echo -e '\e[0;32m This google-chrome theme follows the KaOS color scheme and look \e[0m'
}