# Some colored makepkg-like functions
#!/bin/bash
# tputcolors
post_install() {
	post_upgrade
}

post_upgrade() {
	  echo -e '\e[0;32m To have better password integration with Plasma 5'
	  echo -e '\e[0;32m You can use the KDE Wallet password integration extension'
          echo -e '\e[0;32m Download it from:' 
          echo -e '\e[0;32m https://addons.mozilla.org/en-US/firefox/addon/kde-wallet-password-integratio \e[0m'
}
