#!/bin/bash

if [[ "$DESKTOP_SESSION" == "plasma" ]]; then
        export QTDIR="/usr/lib/qt5"
        export PATH="usr/bin:$QTDIR/bin:$PATH"
	export QT_PLUGIN_PATH="/usr/lib/plugins:/usr/lib/qt5/plugins"
	export QT_INCLUDE_PATH="/usr/include/qt5"
	export QML2_IMPORT_PATH="/usr/lib/qml:/usr/lib/qt5/qml"
	export QML_IMPORT_PATH="$QML2_IMPORT_PATH"
	export KDE_SESSION_VERSION=5
	export KDE_FULL_SESSION=true
fi

