#!/bin/bash

if [[ "$DESKTOP_SESSION" == "kf5-plasma" ]]; then
	export QT_PLUGIN_PATH="/usr/lib/qt5/plugins"
	export QT_INCLUDE_PATH="/usr/include/qt5"
	export QT_BIN_PATH="/usr/lib/qt5/bin"
	export QML2_IMPORT_PATH="/usr/lib/qt5/qml"
	export QML_IMPORT_PATH="/usr/lib/qt5/qml"
	export KDE_SESSION_VERSION=5
	export KDE_FULL_SESSION=true
fi
